"""empty message

Revision ID: 60fd8176468e
Revises: ca51303272ea
Create Date: 2022-03-16 10:08:11.983257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60fd8176468e'
down_revision = 'ca51303272ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('username', sa.String(length=200), nullable=False))
    op.alter_column('logs', 'log_id',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint('logs_ibfk_1', 'logs', type_='foreignkey')
    op.drop_column('logs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('logs_ibfk_1', 'logs', 'users', ['user_id'], ['id'])
    op.alter_column('logs', 'log_id',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_column('logs', 'username')
    # ### end Alembic commands ###
