"""empty message

Revision ID: b24e1272984d
Revises: 60fd8176468e
Create Date: 2022-03-16 10:09:56.956040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b24e1272984d'
down_revision = '60fd8176468e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('user', sa.String(length=200), nullable=False))
    op.drop_column('logs', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('username', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('logs', 'user')
    # ### end Alembic commands ###
